Referenced by issue #99900, Segfault on Linux when running third party Python library function with multithreading enabled
