Referenced by issue #41284, The python ops log doesn't work
