Referenced by issue #90268, Mesh.from_pydata error if using numpy array for edges, faces
