Referenced by issue #97874, Python exception after undo with image space visible
