Referenced by pull request #125296, GPv3: Python error after `active_layer` renaming
Referenced by commit e373625e73d3dfbe68957fed5728f53c2fd942b5, GPv3: Python error after `active_layer` renaming
