Referenced by issue #42966, Py_Initialize: Unable to get the locale encoding
