Referenced by commit 738d942d291, Correct error in recent use of PyC_Long_*
