Referenced by issue #71983, script_pyapi_idprop_datablock test fails
Referenced by issue #71858, Inharitance for `ShaderNodeCustomGroup` is broken
