Referenced by pull request #123097, Fix: PyAPI Doc: unexpected indentation error
