Referenced by issue #62776, face map issue, when created via python
